### ISSUE TITLE
Please install 'idn' command first.

### ISSUE THREAD

**Issue by B45man** [davidjb/turris-omnia-tls#1]
Hi! First of all, thanks for taking the time to create this script for other users. I'm having a minor issue using it, hopefully you can help. I am getting this message when doing the first command of step 6 of your guide:

**It seems that https://*****.zzzz.io is an IDN( Internationalized Domain Names), please install 'idn' command first.**

I am using a dynamic DNS. Any idea what I can change to your script to get it working?

**Comment by davidjb** [comment]
So the certificate issuing in my scripts here use Acme.sh; which is just adding support for wildcard certs now -- see https://github.com/Neilpang/acme.sh/issues/1164#issuecomment-355746240 and the underlying issue https://github.com/Neilpang/acme.sh/issues/934#issuecomment-355738570. 

Seems you can just use the latest released version of Acme.sh (v2.7.7) at time of writing and apparently it will be supported.  That said, it's a bit ambiguous because the issue https://github.com/Neilpang/acme.sh/issues/934 isn't closed as fixed yet and some comments mention only staging is supported.

Give it a go and see what happens.  If you run into trouble with acme.sh erroring, let them know on that related issue on Acme.sh.

Cheers!
